name: "Issue comment"
author: "kyoncy"
description: "comment when open issue"
branding:
  icon: message-circle
  color: blue
inputs:
  token:
    description: "GitHub token for use by this action."
    required: false
    default: ${{ github.token }}
  message:
    description: "Message"
    required: false
    default: |
      Szia! Köszönjük, hogy jelezted a hibát. A fejlesztők már dolgoznak a megoldáson!
runs:
  using: "node12"
  main: "dist/index.js"
